mcs.metadata:
  componentName: GCA - Graph Connector Agent - Generate custom connector Swagger
  description: GCA-GraphConnectorAgent-GeneratecustomconnectorSwagger
kind: TaskDialog
modelDisplayName: Generate custom connector Swagger
modelDescription: Generate a Power Platform-compatible Swagger 2.0 custom connector schema from selected Microsoft Graph API operations. Returns connector name, operation count, and Gist URL.
outputs:
  - propertyName: baseName

  - propertyName: downloadUrls

  - propertyName: gistUrl

  - propertyName: totalOperations

  - propertyName: validationWarnings

action:
  kind: InvokeConnectorTaskAction
  connectionReference: copilots_header_91a5e.shared_gca-20-2d-20deploy-20pipeline-5f251f982b189de9d-2501cc3075c9bd9f.2b47903cf48c4a4aa58a3d67d0da8fbf
  connectionProperties:
    mode: Invoker

  operationId: graph_generateConnector

outputMode: All